/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.vista;

import pe.edu.utp.controller.MenuController;
import pe.edu.utp.dao.UsuarioDao;
import pe.edu.utp.daoImpl.UsuarioDaoImpl;
import pe.edu.utp.dto.InicioSesionDTO;
import pe.edu.utp.dto.SesionUsuario;
import pe.edu.utp.entity.Asistencia;

public class MenuAdmin extends javax.swing.JFrame {

    private MenuController controller;
    private Asistencia modelo;
    private UsuarioDao pdao;
    private InicioSesionDTO usuarioLogeado;

    private void mostrarDatosUsuario() {
        if (usuarioLogeado != null) {
            lblCargo.setText(usuarioLogeado.getNombreCompleto());
        }
    }

    public MenuAdmin(InicioSesionDTO usuarioLogeado) {
        initComponents();
        modelo = new Asistencia();
        pdao = new UsuarioDaoImpl();
        controller = new MenuController(this, modelo, pdao);
        this.usuarioLogeado = usuarioLogeado;
        mostrarDatosUsuario();
        controller.iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblGclientes = new javax.swing.JLabel();
        lblGproductos = new javax.swing.JLabel();
        lblGventas = new javax.swing.JLabel();
        lblGpedidos = new javax.swing.JLabel();
        lblGproveedores = new javax.swing.JLabel();
        lblGusuarios = new javax.swing.JLabel();
        lblGproProveedor = new javax.swing.JLabel();
        lblGcerrarSesion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("A Cargo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 80, 20));

        lblCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(255, 255, 255));
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 120, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¡Bienvenido Administrador!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 560, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/logoinka.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 80));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 750, -1));

        lblGclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/Gestor clientes.png"))); // NOI18N
        lblGclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGclientesMouseClicked(evt);
            }
        });
        jPanel1.add(lblGclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, 130));

        lblGproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/Gestor de Productos.png"))); // NOI18N
        jPanel1.add(lblGproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, 130));

        lblGventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/Gestor de Ventas.png"))); // NOI18N
        jPanel1.add(lblGventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 130));

        lblGpedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/Gestor de Pedidos.png"))); // NOI18N
        jPanel1.add(lblGpedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 150, 130));

        lblGproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/Gestor de proveedores.png"))); // NOI18N
        jPanel1.add(lblGproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 150, 130));

        lblGusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/Gestor de Empleados.png"))); // NOI18N
        jPanel1.add(lblGusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 150, 130));

        lblGproProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/ProductosProveedor.png"))); // NOI18N
        jPanel1.add(lblGproProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 150, 130));

        lblGcerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/salir.png"))); // NOI18N
        jPanel1.add(lblGcerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 150, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/assets/FondoMenuEmpleado.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGclientesMouseClicked

    }//GEN-LAST:event_lblGclientesMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InicioSesionDTO usuarioLogeado = SesionUsuario.getUsuarioLogeado();
                new MenuAdmin(usuarioLogeado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCargo;
    public javax.swing.JLabel lblGcerrarSesion;
    public javax.swing.JLabel lblGclientes;
    public javax.swing.JLabel lblGpedidos;
    public javax.swing.JLabel lblGproProveedor;
    public javax.swing.JLabel lblGproductos;
    public javax.swing.JLabel lblGproveedores;
    public javax.swing.JLabel lblGusuarios;
    public javax.swing.JLabel lblGventas;
    // End of variables declaration//GEN-END:variables
}
